palavra = input('Digite aqui, algo para ter seu tipo analisado. ')
print('O tipo primirivo dessa palavra é: ' , type(palavra))
print(palavra.isalnum())
print(palavra.isalpha())
print(palavra.isascii())
print(palavra.isdecimal())
print('Só tem espaços? ', palavra.isspace())
print(palavra.islower())
print('Está capitalizada? ', palavra.istitle())